/**
 * Created by Jason.liu on 2016-06-14.
 */
export const  RESERVATION_LOAD= 'RESERVATION_LOAD';
export const  RESERVATION_SCAN = 'RESERVATION_SCAN';
export const  RESERVATION_SELECTED = 'RESERVATION_SELECTED';

export const  RESERVATION_GOODS_LOAD = 'RESERVATION_GOODS_LOAD'
export const  RESERVATION_GOODS_SELECTED= 'RESERVATION_GOODS_SELECTED'
export const  PALLET_SCAN ='PALLET_SCAN'
export const  PALLET_ADD = 'PALLET_ADD'
export const  PALLET_REMOVE = 'PALLET_REMOVE'
export const  PALLET_GOODS_CONFIRM = 'PALLET_GOODS_CONFIRM'
export const  PALLET_GOODS_LOAD='PALLET_GOODS_LOAD'
export const GOODS_CHANGE='GOODS_CHANGE'
export const PALLET_SELECTED='PALLET_SELECTED'

export const ADD_IMAGES='ADD_IMAGES'
export const REMOVE_IMAGES='REMOVE_IMAGES'
export const SELECTED_IMAGES = 'SELECTED_IMAGES'
export const SHOW_IMAGES='SHOW_IMAGES'



